name: (Active) Update truth data daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  upload_viz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - name: Free disk space
      run: |
          df --human-readable
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          rm --recursive --force "$AGENT_TOOLSDIRECTORY"
          
    - name: Maximize build space
      uses: easimon/maximize-build-space@v4
      with:
        root-reserve-mb: 4096
        swap-size-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        
    - name: Check space available
      run: df --human-readable

    - name: Checkout covid-19-hub-vizualization repo
      uses: actions/checkout@v2
      with:
        path: Covid-19-Hub-Vizualization
        
    - name: Setup GitHub Action for R language
      uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev
      
    - name: Checkout covidData
      uses: actions/checkout@v2
      with:
        repository: reichlab/covidData
        token: ${{secrets.GH_TOKEN}}
        path: covidData
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install R dependencies 
      working-directory: ./Covid-19-Hub-Vizualization
      run: Rscript install_dependencies.R
      env:
        GITHUB_PAT: ${{ secrets.GH_TOKEN }}

    - name: Install covidData
      run: make all
      working-directory: ./covidData/code/data-processing
    
    - name: Generate truth data 
      run: Rscript preprocess_data/preprocess_truth.R
      working-directory: ./Covid-19-Hub-Vizualization
      
    - name: Push generated files to GitHub
      run: bash ./travis/push-gh.sh
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
      working-directory: ./Covid-19-Hub-Vizualization
        
    - name: Check space available after update
      run: df --human-readable
      working-directory: ./Covid-19-Hub-Vizualization
